- テンソルはNumPyのndarraysに似ているが、PyTorchのテンソルを使うとGPUなどを使って計算ができるっぽい。テンソルの方がより最適化されているという違いがある。
- テンソルとNumPyは同じメモリ空間が使える（？）ので、コピーしなくていいらしい。
  - 参照ってこと？
- テンソルは自動微分に最適化されている

In [1]:
%matplotlib inline
import torch
import numpy as np


# テンソルの初期化
色々やり方があるらしい。
- データから直接テンソルを作る方法もあれば
- NumPy arrayからテンソルに変換する方法もある。

In [2]:
# データからテンソルを作る場合
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
data = [[1, 2],[3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


> 他のテンソルから作成
>他のテンソルから新しいテンソルを作成する場合、明示的に上書きされない限り、引数のテンソルのプロパティ（形状、データ型）を保持します。

どういういみ？？よくわからん。引数にx_dataいるんか？

In [4]:
# x_dataの特性（プロパティ）を維持
x_ones = torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n")

# x_dataのdatatypeを上書き更新
x_rand = torch.rand_like(x_data, dtype=torch.float) 
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6586, 0.0620],
        [0.9132, 0.2886]]) 



## ランダム値や定数のテンソルの作成

shapeは、テンソルの次元を示すタプルです。
以下の例では、shapeからテンソルのサイズを決めています。

In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0919, 0.2131, 0.2052],
        [0.5195, 0.8676, 0.9769]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
# GPUが使用可能であれば、GPU上にテンソルを移動させる
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

じどうびぶんとかいうやつ
具体例として、『y = x^2』という関数を自動微分して、微分した結果『y’ = 2x』に『x = 1』を代入して得られる『2』を出力する方法を下記に示します。

In [8]:
x = torch.tensor(1.0, requires_grad=True)
print(x)
y = x**2
y.backward()
x.grad

tensor(1., requires_grad=True)


tensor(2.)